version: '3.8'

services:
  homebridge:
    build: .
    container_name: homebridge
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./homebridge:/homebridge
    environment:
      - TZ=Europe/Amsterdam
      - HOMEBRIDGE_CONFIG_UI=1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
